// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CurrencyApi.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CurrencyApi.Models;

namespace CurrencyApi.Data
{
    public partial class Dtbankdb1Context : DbContext
    {
        public Dtbankdb1Context()
        {
        }

        public Dtbankdb1Context(DbContextOptions<Dtbankdb1Context> options)
            : base(options)
        {
        }

        public virtual DbSet<RATE> RATE { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-B23N7F1S\\SQLEXPRESS;Initial Catalog=DTBankDB1;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RATE>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

                entity.Property(e => e.TimeStamp).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}